source "https://supermarket.chef.io"

metadata

cookbook "apt"
cookbook "build-essential"
cookbook "mongodb"
cookbook 'nodejs'
cookbook 'ruby_build'
cookbook 'rbenv', git: 'https://github.com/aminin/chef-rbenv'
