source "https://supermarket.chef.io"

metadata

cookbook "apt"
cookbook "build-essential"
cookbook "mongodb"
cookbook 'nodejs'
cookbook "rvm", git: 'git://github.com/mrwinton/chef-rvm.git', branch: "master"
