# encoding: utf-8
# This file originally created at http://rove.io/b1d8d1c8809fa324118e5fa9ce21b275

# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = 'ubuntu/trusty64'
  config.vm.hostname = 'pitchbox'
  config.vm.box_url = 'http://files.vagrantup.com/trusty64.box'
  config.ssh.forward_agent = true
  config.vm.synced_folder '../', '/pitchhub'

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box
  end

  # Forward the Rails server default port to the host
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "172.28.128.3"

  # Use Chef Solo to provision our virtual machine
  config.vm.provision :chef_solo do |chef|

    #Ensure the Chef 12.2.1 is used to provision and install the cookbooks
    chef.version = '12.2.1'
    chef.cookbooks_path = ["cookbooks"]

    chef.add_recipe 'apt'
    chef.add_recipe 'nodejs'
    # RVM for rubies management
    chef.add_recipe "rvm::vagrant"
    chef.add_recipe "rvm::system"
    chef.add_recipe 'mongodb::mongodb_org_repo'
    chef.add_recipe 'mongodb::default'

    $ruby_21_version = "ruby-2.1.5"

    # Install Ruby 2.2.1 and Bundler
    chef.json = {
        # Installing The latest ruby version
        rvm: {
            default_ruby: 'ruby-2.1.5',

            # Installing multiple ruby versions
            rubies: ['ruby-2.1.5'],

            # Gems that will be accessed globally
            global_gems: [
                { name: :thin },
                { name: :bundler }
            ],

            # Somehow needed for Vagrant
            vagrant: {
                system_chef_solo: '/opt/vagrant_ruby/bin/chef-solo'
            }
        }
    }

  end

  #setup pitchhub's helpful aliases
  aliasesPath = File.expand_path("scripts/aliases")
  if File.exists? aliasesPath then
    config.vm.provision "file", source: aliasesPath, destination: "~/.bash_aliases"
  end

end
